spring:
  application:
    name: ai-codeless-app-builder-backend
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/ai_codeless_app_builder
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 123456
      ttl: 3600
  # session
  session:
    store-type: redis
    # session过期时间 30天
    timeout: 2592000
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie过期时间 30天
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hz.aicodelessappbuilder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn